import grpc
import logging
import os
from concurrent import futures
from datetime import datetime

# Generated proto imports
from strategies.proto import trading_pb2
from strategies.proto import trading_pb2_grpc

from strategies.models import Candle, Portfolio
from strategies.rule_based import RSIStrategy, BreakoutStrategy, SmaCrossStrategy
from strategies.ml import MLStrategy

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

class StrategyService(trading_pb2_grpc.StrategyServiceServicer):
    def __init__(self):
        # Cache initialized strategies to avoid re-creating them on every request
        self.strategies = {}
        # Mock portfolio for strategies that need it (stateless strategies don't use history anyway)
        self.mock_portfolio = Portfolio(initial_capital=100000.0, cash=100000.0)
        self.strategy_name = os.environ.get("STRATEGY_NAME", "rsi").lower()

    def _get_strategy(self, symbol: str):
        if symbol not in self.strategies:
            if self.strategy_name == "rsi":
                logger.info(f"Initializing RSI Strategy for {symbol}")
                self.strategies[symbol] = RSIStrategy(symbol=symbol, period=14, oversold=30, overbought=70)
            elif self.strategy_name == "sma_cross":
                logger.info(f"Initializing SMA Cross Strategy for {symbol}")
                self.strategies[symbol] = SmaCrossStrategy(symbol=symbol, fast_period=20, slow_period=50)
            elif self.strategy_name == "breakout":
                logger.info(f"Initializing Breakout Strategy for {symbol}")
                self.strategies[symbol] = BreakoutStrategy(symbol=symbol, lookback_period=20, breakout_multiplier=1.0)
            else:
                logger.warning(f"Unknown strategy {self.strategy_name}, defaulting to RSI")
                self.strategies[symbol] = RSIStrategy(symbol=symbol)
        return self.strategies[symbol]

    def GetSignal(self, request, context):
        try:
            # Convert timestamp string to datetime
            try:
                ts = datetime.fromisoformat(request.timestamp.replace("Z", "+00:00"))
            except ValueError:
                ts = datetime.now()

            # Create Candle object
            candle = Candle(
                symbol=request.symbol,
                timestamp=ts,
                open=request.open,
                high=request.high,
                low=request.low,
                close=request.close,
                volume=request.volume
            )

            # Get strategy instance
            strategy = self._get_strategy(request.symbol)

            # Get signals
            orders = strategy.on_candle(candle, self.mock_portfolio)

            response = trading_pb2.SignalResponse(
                symbol=request.symbol,
                side="NONE",
                size=0.0
            )

            if orders:
                order = orders[0]  # Take the first order
                response.side = order.side.value  # "BUY" or "SELL"
                response.size = order.size
                logger.info(f"Signal generated by {self.strategy_name}: {response.side} {response.size} for {request.symbol}")

            return response

        except Exception as e:
            logger.error(f"Error processing signal request: {e}")
            context.set_details(str(e))
            context.set_code(grpc.StatusCode.INTERNAL)
            return trading_pb2.SignalResponse()

def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    trading_pb2_grpc.add_StrategyServiceServicer_to_server(StrategyService(), server)
    
    port = 50051
    server.add_insecure_port(f'[::]:{port}')
    logger.info(f"Strategy Service started on port {port}")
    server.start()
    server.wait_for_termination()

if __name__ == '__main__':
    serve()
